apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
data:
  username: YXV0aC1hcHA= #base64 для "auth-app"
  password: c2ltcGxlX3Bhc3N3b3Jk  #base64 для "simple_password"
  database: YXV0aF9kYg== #base64 для auth_db